export const GET_ALL_TABLES_SUCCESS = "GET_TABLES_SUCCESS";
export const GET_ALL_TABLES = "GET_TABLES";
export const GET_ALL_TABLES_FAILURE = "GET_TABLES_FAILURE";
export const GET_SINGLE_TABLE = "GET_SINGLE_TABLE";
export const GET_SINGLE_TABLE_SUCCESS = "GET_SINGLE_TABLE_SUCCESS";
export const GET_SINGLE_TABLE_FAILURE = "GET_SINGLE_TABLE_FAILURE";
export const POST_CUSTOMER_TABLE_SUCCESS = "POST_CUSTOMER_TABLE_SUCCESS";
export const POST_CUSTOMER_TABLE = "POST_CUSTOMER_TABLE";
export const POST_CUSTOMER_TABLE_FAILURE = "POST_CUSTOMER_TABLE_FAILURE";
export const GET_ALL_SEATINGS = "GET_ALL_SEATINGS";
export const GET_ALL_SEATINGS_SUCCESS = "GET_ALL_SEATINGS_SUCCESS";
export const GET_ALL_SEATINGS_FAILURE = "GET_ALL_SEATINGS_FAILURE";
export const UPDATE_SEATING_TO_BOOTH = "UPDATE_SEATING_TO_BOOTH";
export const UPDATE_SEATING_TO_BOOTH_SUCCESS =
  "UPDATE_SEATING_TO_BOOTH_SUCCESS";
export const UPDATE_SEATING_TO_BOOTH_FAILURE =
  "UPDATE_SEATING_TO_BOOTH_FAILURE";
export const DELETE_UNSEATED_SEATING = "DELETE_UNSEATED_SEATING";
export const DELETE_UNSEATED_SEATING_SUCCESS =
  "DELETE_UNSEATED_SEATING_SUCCESS";
export const DELETE_UNSEATED_SEATING_FAILURE =
  "DELETE_UNSEATED_SEATING_FAILURE";
export const DELETE_SEATING = "DELETE_SEATED_SEATING";
export const DELETE_SEATING_SUCCESS = "DELETE_SEATED_SEATING_SUCCESS";
export const DELETE_SEATING_FAILURE = "DELETE_SEATED_SEATING_FAILURE";
export const DELETE_SEATING_FROM_BOOTH = "DELETE_SEATING_FROM_BOOTH";
export const DELETE_SEATING_FROM_CUSTOMER = "DELETE_SEATING_FROM_CUSTOMER";
export const PUT_SEATING_TO_BOOTH = "PUT_SEATING_TO_BOOTH";
export const GET_CUSTOMER_INFO = "GET_CUSTOMER_INFO";
export const GET_CUSTOMER_INFO_SUCCESS = "GET_CUSTOMER_INFO_SUCCESS";
export const GET_CUSTOMER_INFO_FAILURE = "GET_CUSTOMER_INFO_FAILURE";
export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS";
export const GET_ALL_CUSTOMERS_FAILURE = "GET_ALL_CUSTOMERS_FAILURE";
export const POST_NEW_CUSTOMER = "POST_NEW_CUSTOMER";
export const POST_NEW_CUSTOMER_SUCCESS = "POST_NEW_CUSTOMER_SUCCESS";
export const POST_NEW_CUSTOMER_FAILURE = "POST_NEW_CUSTOMER_FAILURE";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";
export const GET_MENU = "GET_MENU";
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS";
export const GET_MENU_FAILURE = "GET_MENU_FAILURE";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";
export const POST_ORDER = "PLACE_ORDER";
export const POST_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const POST_ORDER_FAILURE = "PLACE_ORDER_SUCCESS";
export const UPDATE_CUSTOMER_TO_BOOTH = "UPDATE_CUSTOMER_TO_BOOTH";
export const UPDATE_CUSTOMER_TO_BOOTH_SUCCESS =
  "UPDATE_CUSTOMER_TO_BOOTH_SUCCESS";
export const UPDATE_CUSTOMER_TO_BOOTH_FAILURE =
  "UPDATE_CUSTOMER_TO_BOOTH_FAILURE";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const IS_LOADED = "IS_LOADED";
export const REFRESH_SEATINGS = "REFRESH_SEATINGS";
